-- Catálogo de orillas por lote (BRIX).
-- Ejecutar en SQL Server si la tabla no existe.
-- El bootstrap ya incluye loteOrillas en la respuesta.

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.LOTE_ORILLAS_CATALOGO') AND type in (N'U'))
BEGIN
    CREATE TABLE dbo.LOTE_ORILLAS_CATALOGO (
        ID_LOTE_ORILLA INT NOT NULL PRIMARY KEY,
        ID_LOTE INT NOT NULL,
        ORILLA_CODIGO NVARCHAR(50) NOT NULL,
        ORILLA_LABEL NVARCHAR(200) NOT NULL,
        PERIMETRAL_DESCRIPCION NVARCHAR(500) NULL,
        ACTIVO BIT NOT NULL DEFAULT 1,
        CONSTRAINT FK_LOTE_ORILLAS_LOTE FOREIGN KEY (ID_LOTE) REFERENCES dbo.LOTE(ID_LOTE)
    );

    CREATE INDEX IX_LOTE_ORILLAS_ID_LOTE ON dbo.LOTE_ORILLAS_CATALOGO(ID_LOTE);
END
GO
