SET NOCOUNT ON;
GO

IF EXISTS (
    SELECT 1
    FROM dbo.PERSONA_TIPO
    WHERE UPPER(LTRIM(RTRIM(CODIGO))) IN (N'RI', N'RIN', N'RESPONSABLE_INSPECCION')
       OR UPPER(LTRIM(RTRIM(DESCRIPCION))) IN (
            N'RESPONSABLE DE INSPECCION',
            N'RESPONSABLE DE INSPECCIÓN'
       )
)
BEGIN
    UPDATE dbo.PERSONA_TIPO
    SET CODIGO = N'RI',
        DESCRIPCION = N'RESPONSABLE DE INSPECCION',
        ESTADO = 1
    WHERE UPPER(LTRIM(RTRIM(CODIGO))) IN (N'RI', N'RIN', N'RESPONSABLE_INSPECCION')
       OR UPPER(LTRIM(RTRIM(DESCRIPCION))) IN (
            N'RESPONSABLE DE INSPECCION',
            N'RESPONSABLE DE INSPECCIÓN'
       );
END
ELSE
BEGIN
    INSERT INTO dbo.PERSONA_TIPO (CODIGO, DESCRIPCION, ESTADO)
    VALUES (N'RI', N'RESPONSABLE DE INSPECCION', 1);
END
GO
